server:
  port: ${KEEPER_WEB_PORT:8080}

spring:
  application:
    name: HolidayKeeper
  datasource:
    url: ${DB_URL:jdbc:h2:mem:testdb}
    username: ${DB_USERNAME:test}
    password: ${DB_PASSWORD:1234}
    driver-class-name: ${DB_CLASS_NAME:org.h2.Driver}
  jpa:
    database-platform: ${DB_PLATFORM:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: ${JPA_SQL_VIEW:false}
    open-in-view: false
  batch:
    job:
      enabled: false
logging:
  file:
    name: ${LOG_FILE_NAME:holiday_keeper}.log
  level:
    root: ${LOG_ROOT_LEVEL:info}
  logback:
    rollingpolicy:
      max-file-size: 5MB

api:
  holiday:
    host: date.nager.at
    path:
      country: /api/v3/AvailableCountries
      holidays: /api/v3/PublicHolidays