CREATE USER IF NOT EXISTS test PASSWORD '1234';
GRANT ALL ON SCHEMA PUBLIC TO test;

CREATE TABLE country
(
    country_code CHAR(2) NOT NULL,
    country_name VARCHAR(100) NOT NULL,
	created_time TIMESTAMP,
    updated_time TIMESTAMP,
    active       BOOLEAN,
    CONSTRAINT pk_country PRIMARY KEY (country_code)
);

CREATE TABLE holiday
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date         date                                    NOT NULL,
    local_name   VARCHAR(255)                            NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    country_code VARCHAR(2)                              NOT NULL,
    is_fixed     BOOLEAN                                 NOT NULL,
    is_global    BOOLEAN                                 NOT NULL,
    launch_year  INT,
    active       BOOLEAN,
    created_time TIMESTAMP,
    updated_time TIMESTAMP,
    CONSTRAINT pk_holiday PRIMARY KEY (id)
);

CREATE TABLE holiday_counties
(
    holiday_id  BIGINT NOT NULL,
    county_code VARCHAR(6)
);

CREATE TABLE holiday_types
(
    holiday_id BIGINT NOT NULL,
    type       VARCHAR(20)
);

ALTER TABLE holiday_counties
    ADD CONSTRAINT fk_holiday_counties_on_holiday_entity FOREIGN KEY (holiday_id) REFERENCES holiday (id);

ALTER TABLE holiday_types
    ADD CONSTRAINT fk_holiday_types_on_holiday_entity FOREIGN KEY (holiday_id) REFERENCES holiday (id);